### ISSUE TITLE
LOG_DEBUG  on android console

### ISSUE THREAD

**Issue by Shallowmallow** [m-toman/SALB#5]
I'm trying to make SALB work with my own language  in Flite and hts-voice.

I was wondering how to make LOG_DEBUG working on the Android Console
I set in Android.mk
`LOCAL_CFLAGS += -DTTSLOGGER_ENABLE_LOG`

in SALB.cpp I set
`LOG_SETFILE(std::string(szPath) +"/log.txt");`

I can access to the log.txt by a simple trick
`adb shell
run-as APP_NAME `
and then going in in the data/files folder.
log.txt exists but is always empty.

Anyone has an idea ? :)

**Comment by m-toman** [comment]
Hmm, actually I can remember that I used this strange trick here:
https://github.com/m-toman/SALB/blob/master/engine/manager/include/TTSLogger.h#L34-L35
because SAPI seemed to kill my file handles all the time.
Perhaps the first line works better?

The app does seem to have the correct privileges because otherwise it wouldn't be able to create the file?

Sorry I can't help you much more with that, as many others I moved on to DNN-based synthesis ;)
